# Erstellen von Numpy-Arrays

In [1]:
import numpy as np

#np.array(L)

In [2]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
np.ones([8,7])

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [4]:
a = np.zeros([3,3])
a[2,2] = 5
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 5.]])

In [5]:
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a = np.arange(0,10.5,0.5)
a

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [14]:
a = np.linspace(0,1, 11)
a

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [15]:
np.pi * a

array([0.        , 0.31415927, 0.62831853, 0.9424778 , 1.25663706,
       1.57079633, 1.88495559, 2.19911486, 2.51327412, 2.82743339,
       3.14159265])

In [19]:
np.random.random(10)*100

array([85.02796136, 57.83834166, 87.29521745, 49.53857336, 21.20886912,
       73.30682197, 68.52896197, 47.9098261 , 67.81530219,  7.82074031])