Die `python` Datei `numerik.py` mit folgenden Inhalt:

```
import numpy as np

a = np.array([1,2,3,4], dtype=np.float64)
b = np.array(list(range(0,11))) / 10

c = np.array([ [1,2,3],[4,5,6],[7,8,9] ])

new_var = np.random.random(10)
```

lässt sich wie ein normales python Modul importieren (dafür muss die Datei in dem gleichen Ordner gespeichert sein, sonst müsste man die `sys.path` Variable anpassen...).

In [5]:
import numerik
from numerik import new_var

In [6]:
numerik.a

array([1., 2., 3., 4.])

In [7]:
numerik.new_var

array([0.09174527, 0.67208376, 0.43213394, 0.61521954, 0.01456838,
       0.97422008, 0.56476843, 0.67654593, 0.77103929, 0.30915768])

In [8]:
new_var

array([0.09174527, 0.67208376, 0.43213394, 0.61521954, 0.01456838,
       0.97422008, 0.56476843, 0.67654593, 0.77103929, 0.30915768])